### ISSUE TITLE
Exception in thread QueueFeederThread

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agronholm/pythonfutures#10]
```
What steps will reproduce the problem?

1. Create new executor based on the ProcessPoolExecutor
2. Set max_workers=8
3. Submit two tasks to run
4. wait on all futures



What is the expected output? What do you see instead?

No exceptions, program runs to completion.  Instead seeing an exception, unsure 
of cause (sometimes the program runs fine, other times it doesn't).


Program Output (sporadically hits this):

"Exception in thread QueueFeederThread (most likely raised during interpreter 
shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/threading.py", line 484, in run
  File "/usr/lib/python2.6/multiprocessing/queues.py", line 233, in _feed
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
"





What version of the product are you using? On what operating system?

Ubuntu 11.04
Python 2.6.6
```

Original issue reported on code.google.com by `wolfgang...@gmail.com` on 11 Jan 2011 at 1:50

**Comment by agronholm** [comment]
3 years, no feedback -- closing.
