### ISSUE TITLE
pip install futures installation problem -- error stack given below

### ISSUE THREAD

**Issue by ankit01122** [agronholm/pythonfutures#100]
pip install futures
Collecting futures
  Downloading futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 268, in <module>
          monkey.patch_all()
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\monkey.py", line 97, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\monkey.py", line 157, in patch_for_msvc_specialized_c
ompiler
          patch_func(*msvc14('_get_vc_env'))
                      ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\monkey.py", line 147, in patch_params
          mod = import_module(mod_name)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>   
          import unittest.mock as mock
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\unittest\mock.py", line 26, in <module>
          import asyncio
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\asyncio\__init__.py", line 8, in <module>
          from .base_events import *
        File "C:\Users\a4jain\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 18, in <module>
          import concurrent.futures
        File "C:\Users\a4jain\AppData\Local\Temp\pip-install-xiabli5x\futures_21ebacc7751a405b873ecd8f587d1fc8\concurrent\futures\__init__.py", line 8, 
in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "C:\Users\a4jain\AppData\Local\Temp\pip-install-xiabli5x\futures_21ebacc7751a405b873ecd8f587d1fc8\concurrent\futures\_base.py", line 357   
          raise type(self._exception), self._exception, self._traceback
                                     ^
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by agronholm** [comment]
Have you read the README? The second sentence says:
> It does not work on Python 3 due to Python 2 syntax being used in the codebase. Python 3 users should not attempt to install it, since the package is already included in the standard library.

Why are you trying to install this on Python 3?
