### ISSUE TITLE
pypy compat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agronholm/pythonfutures#27]
```
What steps will reproduce the problem?
1. run testsuite under pypy
2.
3.

What is the expected output? What do you see instead?
pass all. 1 hang and an outrgiht fail

What version of the product are you using? On what operating system?
futures-2.1.6

Please provide any additional information below.

does a hang @


test_del_shutdown (__main__.ProcessPoolShutdownTest) ...

On removing those two instances, then

```python
======================================================================
FAIL: test_repr (__main__.FutureTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_futures.py", line 577, in test_repr
    '<Future at 0x[0-9a-f]+ state=pending>')
AssertionError: Regexp didn't match: '<Future at 0x[0-9a-f]+ state=pending>' 
not found in '<Future at 0x7f2ad3bf26e8L state=pending>'

----------------------------------------------------------------------
Ran 56 tests in 46.216s

FAILED (failures=1)
Traceback (most recent call last):
  File "app_main.py", line 72, in run_toplevel
  File "test_futures.py", line 723, in <module>
    test_main()
  File "test_futures.py", line 46, in decorator
    return func(*args)
  File "test_futures.py", line 718, in test_main
    ThreadPoolShutdownTest)
  File "/usr/lib64/pypy/lib-python/2.7/test/test_support.py", line 1144, in run_unittest
    _run_suite(suite)
  File "/usr/lib64/pypy/lib-python/2.7/test/test_support.py", line 1098, in _run_suite
    raise TestFailed(err)
TestFailed: Traceback (most recent call last):
  File "test_futures.py", line 577, in test_repr
    '<Future at 0x[0-9a-f]+ state=pending>')
AssertionError: Regexp didn't match: '<Future at 0x[0-9a-f]+ state=pending>' 
not found in '<Future at 0x7f2ad3bf26e8L state=pending>'
```

I don't see any benefit in a full log. Do you?

```

Original issue reported on code.google.com by `del...@iinet.com.au` on 5 May 2014 at 4:47

**Comment by agronholm** [comment]
Is this still relevant?

**Comment by amcgregor** [comment]
Does the current test suite currently fail on pypy?  If yes, does that patch still apply?  If yes, apply it?  :P

**Comment by agronholm** [comment]
The current test suite passes on PyPy. I guess I'll just close this then.
