### ISSUE TITLE
Support Python3 in tests

### ISSUE THREAD

**Issue by domenkozar** [agronholm/pythonfutures#46]
```

======================================================================
ERROR: test_futures (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: test_futures
Traceback (most recent call last):
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python3.4-futures-3.0.2.drv-0/futures-3.0.2/test_futures.py", line 10, in <module>
    from StringIO import StringIO
ImportError: No module named 'StringIO'
```

**Comment by agronholm** [comment]
Why are you trying to build this on Python 3.4? You can just import concurrent.futures normally without installing anything. This project is a **backport** of that package to Python 2.
