### ISSUE TITLE
syntax error with raise type(self._exception), self._exception, self._traceback when pip install futures in python 3.9

### ISSUE THREAD

**Issue by ThePythoniousGuy** [agronholm/pythonfutures#98]
Hi! I got the following error when installing futures.

pip install futures

```
Collecting futures
  Using cached futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "c:\users\osama\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "c:\users\osama\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 32, in <module>
          from setuptools.extern.more_itertools import unique_everseen
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 565, in module_from_spec
        File "c:\users\osama\appdata\local\programs\python\python39\lib\site-packages\setuptools\extern\__init__.py", line 52, in create_module
          return self.load_module(spec.name)
        File "c:\users\osama\appdata\local\programs\python\python39\lib\site-packages\setuptools\extern\__init__.py", line 37, in load_module
          __import__(extant)
        File "c:\users\osama\appdata\local\programs\python\python39\lib\site-packages\setuptools\_vendor\more_itertools\__init__.py", line 1, in <module>
          from .more import *  # noqa
        File "c:\users\osama\appdata\local\programs\python\python39\lib\site-packages\setuptools\_vendor\more_itertools\more.py", line 5, in <module>
          from concurrent.futures import ThreadPoolExecutor
        File "C:\Users\osama\AppData\Local\Temp\pip-install-negdh8jb\futures_81c5b63789b441bcb23d21120074005a\concurrent\futures\__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "C:\Users\osama\AppData\Local\Temp\pip-install-negdh8jb\futures_81c5b63789b441bcb23d21120074005a\concurrent\futures\_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

My system info:
**Windows 10 PE AMD64
Python 3.9.7**

**Comment by agronholm** [comment]
You should not try to install futures on Python 3. It's a backport of the `concurrent.futures` package to Python 2.
